comment:
  image:
    repository: dmitryshomrin/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: dmitryshomrin/post
    tag: latest
    service:
      externalPort: 5000

ui:
  image:
    repository: dmitryshomrin/ui
    tag: latest
    service:
      externalPort: 9292
