global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#dmitry_shomrin'
