version: '3.3'
services:
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      - prom
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    networks:
      - prom
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  node-exporter-mongo:
    image: ${USERNAME}/mongod_exporter:1.0
    command:
      - '-mongodb.uri=mongodb://post_db:27017'
    networks:
      - prom

  cloudprober:
    image: ${USERNAME}/cloudprober:1.0
    networks: 
      - prom
    ports:
      - '9313:9313'

  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    networks: 
      - prom
    ports:
      - '8080:8080'

  grafana:
    image: grafana/grafana:5.0.0
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    networks: 
      - prom
    ports:
      - 3000:3000

  alertmanager:
    image: ${USER_NAME}/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    networks: 
      - prom
    ports:
      - 9093:9093

volumes:
  prometheus_data:
  grafana_data:

networks:
  prom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
