version: '3.3'
services:
  post_db:
    image: mongo:${DB_VER}
    volumes:
      - post_db:/data/db
    networks:
      prom:
        aliases:
          - comment_db
          - post_db
  ui:
    image: ${USERNAME}/ui #:${UI_VER}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - prom
  post:
    image: ${USERNAME}/post #:${POST_VER}
    networks:
      - prom
  comment:
    image: ${USERNAME}/comment #:{COMMENT_VER}
    networks:
      - prom

volumes:
  post_db:

networks:
  prom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
