version: '3.3'
services:
  post_db:
    image: mongo:${DB_VER}
    volumes:
      - post_db:/data/db
    networks:
      prom:
        aliases:
          - comment_db
          - post_db
  ui:
    image: ${USERNAME}/ui #:${UI_VER}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - prom
  post:
    image: ${USERNAME}/post #:${POST_VER}
    networks:
      - prom
  comment:
    image: ${USERNAME}/comment #:{COMMENT_VER}
    networks:
      - prom

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      - prom
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    networks:
      - prom
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  node-exporter-mongo:
    image: ${USERNAME}/mongod_exporter:1.0
    command:
      - '-mongodb.uri=mongodb://post_db:27017'
    networks:
      - prom

  cloudprober:
    image: ${USERNAME}/cloudprober:1.0
    networks: 
      - prom
    ports:
      - '9313:9313'

volumes:
  prometheus_data:
  post_db:

networks:
  prom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
